### PR TITLE
Cheat sheet small fix

### PR DESCRIPTION
**Pull request by artivis**
Replace constraint `R^T R = I` by `M^{-1} M = I` for `SE2` and `SE3`.

### CODE REVIEW

**Comment by joansola** [comment]
Last minute recall: `M.tr * M = I` is actually wrong!

**Comment by artivis** [comment]
ah crap, fixing the fix...

**Comment by artivis** [comment]
Done.

**Comment by artivis** [comment]
For some uploading from the web interface does not seem to work. I'll upload again from the cli asap.

**Comment by joansola** [comment]
I still see `M.tr*M=I`. Valid constraints are either `R.tr*R+I` (precise constraint) or the general `M.inv*M=I` (general abstract constraint). I prefer `R.tr*R+I`.

**Comment by artivis** [comment]
> I prefer `R.tr*R+I`.

You mean `R.tr*R=I`? As it currently is on master? If so let's close this PR and keep the current status.

**Comment by artivis** [comment]
Let's stick with the current status (`R.tr*R=I`) since it seems to be preferred. Closing

**Pull request closed without merging**
