### PR TITLE
[WIP] Add SE2 IEKF example

### LINKED ISSUE #218: Cannot compile se2_localization_liekf.cpp on osx with clang
Compiler
```
vermicelle:build jsola$ cpp --version
Apple LLVM version 10.0.1 (clang-1001.0.46.4)
Target: x86_64-apple-darwin18.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```

Error
```
/Users/jsola/dev/manif/examples/se2_localization_liekf.cpp:131:9: error: non-constant-expression cannot be narrowed from
      type 'unsigned long' to 'std::__1::linear_congruential_engine<unsigned int, 48271, 0, 2147483647>::result_type'
      (aka 'unsigned int') in initializer list [-Wc++11-narrowing]
        static_cast<long unsigned int>(std::chrono::high_resolution_clock::now().time_since_epoch().count())
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/jsola/dev/manif/examples/se2_localization_liekf.cpp:131:9: note: insert an explicit cast to silence this issue
        static_cast<long unsigned int>(std::chrono::high_resolution_clock::now().time_since_epoch().count())
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
        static_cast<result_type>(                                                                           )
```

### PR DESCRIPTION
**Pull request by artivis**
Add 'right', 'left' and 'mixed' Invariant Extended Kalman Filter example based on:

- application in chapter 4.3 in the thesis 'Non-linear state error based extended Kalman filters with applications to navigation' A. Barrau.
- adapted after the sample problem presented in chapter 4.1 in the thesis 'Practical Considerations and Extensions of the Invariant Extended Kalman Filtering Framework' J. Arsenault

Works most of the time :p 

Closes #218

### CODE REVIEW

**Comment by artivis** [comment]
Those examples can now be found in [kalmanif](https://github.com/artivis/kalmanif).
Closing this PR.

**Comment by Chris7462** [comment]
Can we bring the [examples/se2_localization_liekf.cpp ](https://github.com/artivis/manif/pull/203/files#diff-a0199449b58ed7c0be2002ebe356befd402aafc366bafbe94f4aba026549cf69) file back into the `manif/examples` directory? I was looking for an example of GPS-like measurements for fusions and finally found it here.

**Comment by artivis** [comment]
I'd prefer not to. This is a Kalman filter example and is thus better located in [kalmanif](https://github.com/artivis/kalmanif), a Kalman filters-related project.
However If you want to contribute it I could accept a PR. But note that the code in this closed PR isn't correct/working properly.

**Comment by Chris7462** [comment]
Thank you. The demo_se2.cpp in kalmanif is good enough for reference. I should have go over the kalmanif first before I leave the comments here. Really appreciate it.

**Pull request closed without merging**
