### PR TITLE
Adding Ceres::Jet unit tests

### PR DESCRIPTION
**Pull request by artivis**
Using `Ceres::Jet` (autodiff), compute the Jacobians below and compare them against `manif` analytic one.

All Jacobians in `manif` are tested:
- inverse
- rplus
- lplus
- rminus
- lminus
- log
- compose
- between
- act

Depends on #199 for the `act` test.

### CODE REVIEW

**Comment by artivis** [comment]
@joansola FYI.
Altho it seems to work, we will have to discuss (later) a jacobian in this PR. I'm computing a local-parameterization **inverse** Jacobian that I'm not sure about - or a local-deparameterization Jacobian of some sort.

**Comment by joansola** [comment]
We DID discuss this Jacobian parametrization inverse no? Is there any other point of conflict?

**Comment by joansola** [comment]
Where are the Jacobians tested / where are the results of these tests? Are there mere ctest cases?

**Comment by artivis** [comment]
> Where are the Jacobians tested / where are the results of these tests? Are they mere ctest cases?

Yes they are ctests (a gtest class) wrapped in a macro for convenience, see [`ceres_test_utils.h`](https://github.com/artivis/manif/blob/97a65bb0585f471f5fc7dfc9a99cdac7456e13bb/test/ceres/ceres_test_utils.h).

**Comment by artivis** [comment]
> We DID discuss this Jacobian parametrization inverse no? Is there any other point of conflict?

We did discuss it indeed and except for some notation we were agree in principle.

**Comment by joansola** [comment]
What do you want me to review then? I can  just approve, if tests pass and the principles are agreed, I would approve. Your opinion?

**Comment by artivis** [comment]
> What do you want me to review then? I can just approve, if tests pass and the principles are agreed, I would approve. Your opinion?

Yeah you can approve. Those tests were not really needed since we already are checking the Jacobians in `manif`. They test for the compatibility with `Ceres::Jet` more than the maths.

**Comment by joansola** [comment]
Yea true. OK

**Review by joansola — APPROVED** [review]
All agreed

**Pull request merged**
