### PR TITLE
Enable github actions

### LINKED ISSUE #184: Travis-CI recent limitation
Travis-CI has recently introduced some serious limitation to their free plan. As a result, all current PRs checks are now stall since we burned all of the free credit over a few CI run. There is no (free) CI credit left.

We need to investigate workarounds and alternatives (e.g. Github Actions) ...

Edit:
Some related readings,
- [Travis new pricing model blog post](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing)
- ["Travis CI's new pricing plan threw a wrench in my open source works"](https://www.jeffgeerling.com/blog/2020/travis-cis-new-pricing-plan-threw-wrench-my-open-source-works)

So as per my understanding, Travis free credits for open source project won't replenish automatically. Instead, one has to ask Travis, on a monthly basis, for some free credits supporting OSS. Reading about some large OSS projects going down this path it seems to be a real pain. Some have no news in a month. I certainly don't want to go down that path so I'll look up for migrating to Github Actions which seems to still be free for public project at that time.

### PR DESCRIPTION
**Pull request by artivis**
Enable Github actions CI to replace Travis CI.

Not a 1-to-1 replacement of Travis but this test matrix covers a somewhat more meaningful set of cases. The only job missing at the moment is the arm64 build.

Closes #184

### CODE REVIEW

**Comment by artivis** [comment]
@joansola This PR is ready for review. I'll hold all other PRs until this is merged and we get CI back up and running.

**Review by joansola — COMMENTED** [review]
I do not understand much here. I just see that Windows is not among the new platforms, and that one test is not passing. I'll just comment by now waiting for a comment from your part before approving.

**Comment by artivis** [comment]
This PR does not change anything for the Windows job which is run on a different platform (AppVeyor - [see here for this PR run](https://ci.appveyor.com/project/artivis/manif/builds/36773190)).
As for the failing test, it is a code coverage check which can be safely ignored.

**Review by joansola — APPROVED** [review]
Based on the last comments, I approve this review

**Pull request merged**
