### PR TITLE
Permit to specify Python package install dir with MANIFPY_PKGDIR

### PR DESCRIPTION
**Pull request by traversaro**
After https://github.com/artivis/manif/commit/a12b09ae77c72dd8c19cce76ca915b1cbdf581e5, it is not anymore possible to install the Python bindings in an installation prefix different from the one of Python, i.e. the Python files would be installed by default outside the `CMAKE_INSTALL_PREFIX`, in `/usr` and `/usr/local`.

Without changing the default behaviour, this PR permits to users that are compiling the manifpy Python library to specify the desired location for the installation by setting the `MANIFPY_PKGDIR` CMake variable to the desired directory.

### CODE REVIEW

**Comment by traversaro** [comment]
An example of use of this feature is https://github.com/robotology/robotology-superbuild/pull/1302 .

**Comment by traversaro** [comment]
> Sorry this completely fell off my radar.

No problem! 

> This change seems reasonable, altho I don't know if there is some established patterns for this (mostly concerned about the variable naming). Would you know any other example?

To be honest most packages I can think of do not have this exact CMake structure, so I do not know if we can take inspiration for variable naming.

**Comment by artivis** [comment]
> To be honest most packages I can think of do not have this exact CMake structure, so I do not know if we can take inspiration for variable naming.

Eheh, fair enough. I'll merge then.

**Review by artivis — APPROVED** [review]

**Comment by traversaro** [comment]
Thanks @artivis !

**Pull request merged**
