### PR TITLE
Add support for autodiff

### LINKED ISSUE #143: Include operator()(int idx) for manif tangent-types?
Dear all, 
I would like to ask whether you would consider it meaningful to introduce the following operator for manif tangent-types, in order to allow direct access to single elements of the coefficient vector of the tangent objects.
I would suggest something along the lines of [this](https://eigen.tuxfamily.org/dox/classEigen_1_1DenseCoeffsBase_3_01Derived_00_01WriteAccessors_01_4.html#ae6ba07bad9e3026afe54806fdefe32bb)
A trivial way to implement the const-version would be to include the following into `tangent_base.h`
```
Scalar operator()(int idx) const {return coeffs()(idx);}
```

### LINKED ISSUE #196: autodiff (library) support
Make sure `manif` supports [`autodiff`](https://github.com/autodiff/autodiff/) and add some tests.

See discussion [here on](https://github.com/artivis/manif/pull/194#issuecomment-753373237).

### PR DESCRIPTION
**Pull request by artivis**
#  Add support for the **autodiff** library 

**autodiff** *automatic differentiation made easier for C++* ([web](https://autodiff.github.io/) - [github](https://github.com/autodiff/autodiff/)).

This PR only adds support for the `autodiff::dual` type.

Find a doc page [here](https://github.com/artivis/manif/blob/f464fe2c028c886ae98facc571c30389fb450d2b/docs/pages/cpp/autodiff.md) (mostly copied from the Ceres/Jet doc page).

The Jacobians produced by **autodiff** are compared against **manif** analytics ones in unit tests.

Also adds 
- `operator[](i)` to both groups and tangents to access single elements of the underlying vector
- `size()` to both groups and tangents which return the underlying vector size (`== RepSize`)

Closes #196.
Closes #143.

### CODE REVIEW

**Comment by artivis** [comment]
@joansola, this is ready for review/approval.

**Review by joansola — COMMENTED** [review]
Seems good to me. I have not tested it, though.

What exactly is the `autodiff` package?

**Comment by artivis** [comment]
> What exactly is the `autodiff` package?

It's a modern (C++17) library for automatic differentiation that provides a scalar type and a few neat functions. Think `ceres::Jet` and the bits to evaluate the Jacobians.

Here is a striped down example (yet nearly compilable):

```cpp
using dual = autodiff::dual;

// cost function
auto fun = [](const auto& measurement, const auto& state_i, const auto& state_j){
  return measurement - (state_j - state_i);
};

SE3<dual> xi, xj;
SE3Tangent<dual> meas_ij, e;

// cost function Jacs wrt underlying vector
Eigen::MatrixXd J_e_xi = autodiff::jacobian(fun, autodiff::wrt(xi), autodiff::at(meas_ij, xi, xj), e);
Eigen::MatrixXd J_e_xj = autodiff::jacobian(fun, autodiff::wrt(xj), autodiff::at(meas_ij, xi, xj), e);

// Local param Jacs
Eigen::MatrixXd J_xi_xiw0 = manif::autodiffLocalParameterizationJacobian<dual>(xi);
Eigen::MatrixXd J_xj_xjw0 = manif::autodiffLocalParameterizationJacobian<dual>(xj);

// cost function Jacs wrt local perturbation on the tangent space
Eigen::MatrixXd J_e_xiw0 = J_e_xi * J_xi_xiw0;
Eigen::MatrixXd J_e_xjw0 = J_e_xj * J_xj_xjw0;
```

Find more examples in the [unit tests](https://github.com/artivis/manif/blob/f464fe2c028c886ae98facc571c30389fb450d2b/test/autodiff/gtest_common_tester_autodiff.h#L168).

**Review by joansola — APPROVED** [review]
Great!

**Pull request merged**
