### PR TITLE
Fix Windows compilation

### LINKED ISSUE #148: Unable to compile the library on VisualStudio2019
Hi all, I'm trying to build `manif` on `VisualStudio2019`. When I configure the cmake project I get the following error:
```
Selecting Windows SDK version 10.0.18362.0 to target Windows 10.0.17134.
The CXX compiler identification is MSVC 19.26.28806.0
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Enterprise/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Performing Test COMPILER_SUPPORTS_CXX11
Performing Test COMPILER_SUPPORTS_CXX11 - Failed
CMake Error at CMakeLists.txt:15 (message):
  The compiler C:/Program Files (x86)/Microsoft Visual
  Studio/2019/Enterprise/VC/Tools/MSVC/14.26.28801/bin/Hostx64/x64/cl.exe has
  no C++11 support.  Please use a different C++ compiler.


Configuring incomplete, errors occurred!
See also "C:/Users/gromualdi/robot-code/manif/build/CMakeFiles/CMakeOutput.log".
See also "C:/Users/gromualdi/robot-code/manif/build/CMakeFiles/CMakeError.log".
```

Associated issue: https://github.com/GiulioRomualdi/lie-group-controllers/pull/1#issuecomment-667695626

### PR DESCRIPTION
**Pull request by GiulioRomualdi**
This PR fixes #148 

cc @traversaro @prashanthr05

### CODE REVIEW

**Comment by artivis** [comment]
Hi, thanks for the PR.
I'm not familiar with VS so the time for me to catch up on what this does and I'll look into it asap!

**Comment by GiulioRomualdi** [comment]
@artivis
> I'm not familiar with VS so the time for me to catch up on what this does and I'll look into it asap!

Thank you very much! I can drop here some related links that can help you to catch up on the problem:
- https://stackoverflow.com/questions/49093833/cmake-3-10-not-working-at-all-with-visual-studio-2015-2017
- https://stackoverflow.com/questions/37621342/cmake-will-not-compile-to-c-11-standard

**Comment by artivis** [comment]
> Thank you very much! I can drop here some related links that can help you to catch up on the problem:
> 
> * https://stackoverflow.com/questions/49093833/cmake-3-10-not-working-at-all-with-visual-studio-2015-2017
> * https://stackoverflow.com/questions/37621342/cmake-will-not-compile-to-c-11-standard

Thanks for the links @GiulioRomualdi. My understanding is that this PR does 2 different things,
- Firstly, it avoid checking for c++11 capability in CMake with MSVC as it is bound to fail. This is fine, but I'm surprised that this was not picked up earlier in [CI](https://github.com/artivis/manif/blob/devel/appveyor.yml) since we [do run VS](https://ci.appveyor.com/project/artivis/manif). Any idea what's up?
- Secondly, it exports the DLL interface using a global CMake variable since `manif` does not do so in code (e.g. `__declspec(dllexport)`). My question here is, is that really `manif`'s job? Since it is a header only library it does not generate any lib/dll therefore I don't think it has to do these exports. That's the 'client' library job. I might be wrong tho.

**Comment by GiulioRomualdi** [comment]
> Secondly, it exports the DLL interface using a global CMake variable since manif does not do so in code (e.g. `__declspec(dllexport))`. My question here is, is that really manif's job? Since it is a header only library it does not generate any lib/dll therefore I don't think it has to do these exports. That's the 'client' library job. I might be wrong tho.

you are actually right. `__declspec(dllexport))` is not required in this case.

**Comment by artivis** [comment]
> you are actually right. `__declspec(dllexport))` is not required in this case.

My question really was, is the flag `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` introduced by this PR really necessary?

**Comment by GiulioRomualdi** [comment]
> > you are actually right. `__declspec(dllexport))` is not required in this case.
> 
> My question really was, is the flag `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` introduced by this PR really necessary?

No, it was not necessary. My fault. I'm sorry.

**Comment by artivis** [comment]
No problem @GiulioRomualdi! I just wanted to be sure.

**Comment by GiulioRomualdi** [comment]
@artivis in https://github.com/artivis/manif/pull/149/commits/c010a31dec3b08f02b55c57f5b4c73db2e292461 I removed  `CMAKE_WINDOWS_EXPORT_ALL_SYMBOLS` from the main `CMakeLists.txt` file.  I compile the library on my machine and everything is working fine

**Comment by abtabrizi** [comment]
Hi @GiulioRomualdi could you provide the detailed steps on how to build `manif` on `VisualStudio`?

**Comment by GiulioRomualdi** [comment]
Hi @abtabrizi if you want to install manif on Windows you may use conda
```console
conda install -c conda-forge manif
```

**Comment by abtabrizi** [comment]
I have it installed, @GiulioRomualdi what command do you run to compile and build one of the `cpp` examples?

**Pull request merged**
